# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "170d9a5a-7e61-4d0f-8908-f16ec4daf847",
# META       "default_lakehouse_name": "AI_ML_LakeHouse",
# META       "default_lakehouse_workspace_id": "d7ae502d-247b-4ea5-857f-127fff869a69",
# META       "known_lakehouses": [
# META         {
# META           "id": "170d9a5a-7e61-4d0f-8908-f16ec4daf847"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# # 06- Machine Learning
# 
# ## Overview
# 
# This notebook represents the Machine Learning layer of the Enterprise AI Platform.
# 
# The primary objective of this notebook is to transform business-ready Gold data into machine learning features, train predictive models, generate business predictions, and Save reusable machine learning assets.
# 
# Unlike the Business Models layer, which focuses on analytical reporting, this layer focuses on predictive intelligence by preparing feature datasets, training machine learning models, and producing prediction tables that can be consumed by downstream AI applications, SQL Analytics Endpoint, Semantic Models, and Power BI.
# 
# ---
# 
# ## Objectives
# 
# The objectives of this notebook are:
# 
# - Read curated Business Models (Gold) Delta tables.
# - Engineer reusable customer, product, and sales features.
# - Create enterprise feature datasets for machine learning.
# - Train and evaluate predictive machine learning models.
# - Register trained models using MLflow.
# - Generate batch predictions.
# - Save machine learning feature and prediction Delta tables.
# 
# ---
# 
# ## Input Tables
# 
# This notebook consumes the following Business Models (Gold) tables created in Notebook 05:
# 
# ### Dimension Tables
# 
# - Business_Models_dim_customer
# - Business_Models_dim_product
# - Business_Models_dim_seller
# - Business_Models_dim_calendar
# - Business_Models_dim_geography
# 
# ### Fact Tables
# 
# - Business_Models_fact_sales
# 
# ---
# 
# ## Output Tables
# 
# ### Machine Learning Feature Tables
# 
# - Machine_Learning_feature_customer
# - Machine_Learning_feature_product
# - Machine_Learning_feature_sales
# 
# ### Machine Learning Prediction Tables
# 
# - Machine_Learning_prediction_sales
# - Machine_Learning_prediction_churn
# 
# ---
# 
# ## Machine Learning Workflow
# 
# Business Models (Gold)
# → Feature Engineering
# → Feature Store
# → Model Training (MLflow)
# → Model Evaluation
# → Batch Prediction
# → Machine Learning Delta Tables
# 
# ---
# 
# ## Downstream Consumers
# 
# The outputs generated by this notebook will be consumed by:
# 
# - AI Engineering Layer
# - AI Agent
# - SQL Analytics Endpoint
# - Semantic Model
# - Power BI


# CELL ********************

# Cell 1:
# ============================================================
# Import Required Libraries
# ============================================================

# PySpark SQL Functions
from pyspark.sql.functions import *

# Window Functions
from pyspark.sql.window import Window

# Machine Learning Libraries
from pyspark.ml.feature import (
    VectorAssembler,
    StringIndexer,
    OneHotEncoder
)

from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.classification import RandomForestClassifier

from pyspark.ml.evaluation import (
    RegressionEvaluator,
    BinaryClassificationEvaluator
)

# MLflow
import mlflow
import mlflow.spark

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 2:
# ============================================================
# Helper Functions
# ============================================================

def validate_dimension(df, table_name):
    print("=" * 80)
    print(f"{table_name} Summary")
    print("=" * 80)

    print(f"Total Records : {df.count()}")
    print(f"Total Columns : {len(df.columns)}")

    display(df.limit(10))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Step 1: Read Business Models (Gold) Delta Tables
# 
# ## Overview
# 
# This step loads the curated Business Models (Gold) Delta tables created in **Notebook 05**.
# 
# These tables represent the trusted business layer of the Enterprise AI Platform and serve as the foundation for all downstream machine learning activities.
# 
# The loaded datasets will be used to:
# 
# - Engineer reusable machine learning features
# - Train predictive machine learning models
# - Generate batch predictions
# - Save Machine Learning Delta tables for downstream AI applications
# 
# ---
# 
# ## Input Tables
# 
# ### Dimension Tables
# 
# - Business_Models_dim_customer
# - Business_Models_dim_product
# - Business_Models_dim_seller
# - Business_Models_dim_calendar
# - Business_Models_dim_geography
# 
# ### Fact Table
# 
# - Business_Models_fact_sales
# 
# ---
# 
# ## Expected Output
# 
# The loaded Business Models (Gold) tables will be used to create:
# 
# ### Machine Learning Feature Tables
# 
# - Machine_Learning_feature_customer
# - Machine_Learning_feature_product
# - Machine_Learning_feature_sales
# 
# ### Machine Learning Prediction Tables
# 
# - Machine_Learning_prediction_sales
# - Machine_Learning_prediction_churn


# CELL ********************

# Cell 3:
# ============================================================
# Read Business Models (Gold) Delta Tables
# ============================================================

# Dimension Tables
Business_Models_dim_customer = spark.table("Business_Models_dim_customer")
Business_Models_dim_product = spark.table("Business_Models_dim_product")
Business_Models_dim_seller = spark.table("Business_Models_dim_seller")
Business_Models_dim_calendar = spark.table("Business_Models_dim_calendar")
Business_Models_dim_geography = spark.table("Business_Models_dim_geography")

# Fact Table
Business_Models_fact_sales = spark.table("Business_Models_fact_sales")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 4:
# ============================================================
# Validation
# ============================================================

validate_dimension(Business_Models_dim_customer, "Business_Models_dim_customer")

validate_dimension(Business_Models_dim_product, "Business_Models_dim_product")

validate_dimension(Business_Models_dim_seller, "Business_Models_dim_seller")

validate_dimension(Business_Models_dim_calendar, "Business_Models_dim_calendar")

validate_dimension(Business_Models_dim_geography, "Business_Models_dim_geography")

validate_dimension(Business_Models_fact_sales, "Business_Models_fact_sales")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Step 2: Feature Engineering Strategy
# 
# ## Overview
# 
# Feature Engineering is the process of transforming business data into meaningful variables (features) that can be used by machine learning models to learn patterns and make predictions.
# 
# Unlike traditional reporting datasets, feature tables are specifically designed to improve the performance, accuracy, and reusability of machine learning models.
# 
# ---
# 
# ## Why Feature Engineering?
# 
# The Business Models (Gold) layer provides clean, trusted business data.
# 
# However, machine learning models cannot effectively learn from raw business transactions alone. Instead, they require engineered features that represent customer behaviour, product performance, and sales trends.
# 
# This notebook creates reusable feature tables that can be shared across multiple machine learning models rather than engineering features separately for every model.
# 
# ---
# 
# ## Feature Tables
# 
# Three enterprise feature tables will be created:
# 
# ### Machine_Learning_feature_customer
# 
# Contains customer-level behavioural features such as purchasing history, spending patterns, payment behaviour, and review metrics.
# 
# ---
# 
# ### Machine_Learning_feature_product
# 
# Contains product-level performance features including sales volume, revenue, delivery performance, customer ratings, and freight characteristics.
# 
# ---
# 
# ### Machine_Learning_feature_sales
# 
# Contains transaction-level sales features that combine customer, product, seller, calendar, and geography information for predictive modelling.
# 
# ---
# 
# ## Benefits
# 
# This design provides:
# 
# - Reusable feature datasets
# - Reduced duplication across ML models
# - Consistent feature definitions
# - Improved model maintainability
# - Scalable enterprise machine learning architecture
# 
# ---
# 
# ## Workflow
# 
# Business Models (Gold)
# 
# ↓
# 
# Feature Engineering
# 
# ↓
# 
# Feature Tables
# 
# ↓
# 
# Machine Learning Models
# 
# ↓
# 
# Predictions
# 
# ↓
# 
# AI Engineering


# MARKDOWN ********************

# # Step 3: Create Customer Feature Table
# 
# ## Overview
# 
# This step creates the **Machine_Learning_feature_customer** table.
# 
# The table contains one record per customer and includes engineered features derived from historical purchasing behaviour, payment patterns, delivery performance, and customer satisfaction.
# 
# These features will serve as reusable inputs for multiple machine learning models, including customer churn prediction, customer segmentation, recommendation systems, and customer lifetime value analysis.
# 
# ---
# 
# ## Output Table
# 
# - Machine_Learning_feature_customer
# 
# ## Grain
# 
# - One row per customer
# 
# ## Primary Key
# 
# - Customer_SK

# CELL ********************

# Cell 5:
# ============================================================
# Create Machine_Learning_feature_customer
# ============================================================

Machine_Learning_feature_customer = (

    Business_Models_fact_sales

    .groupBy("Customer_SK")

    .agg(

        # Customer Activity
        countDistinct("Order_ID").alias("Total_Orders"),
        count("Order_Item_ID").alias("Total_Items_Purchased"),
        round(sum("Total_Item_Value"), 2).alias("Total_Spent"),
        round(avg("Total_Item_Value"), 2).alias("Average_Order_Value"),

        # Payment Behaviour
        round(avg("Payment_Value"), 2).alias("Average_Payment_Value"),
        round(avg("Payment_Installments"), 2).alias("Average_Installments"),
        concat_ws(", ", collect_set("Payment_Type")).alias("Preferred_Payment_Type"),

        # Delivery Behaviour
        round(avg("Delivery_Days"), 2).alias("Average_Delivery_Days"),
        round(avg("Delivery_Delay_Days"), 2).alias("Average_Delivery_Delay"),

        round(
            avg(
                when(col("Delivery_Performance") == "On Time", 1)
                .otherwise(0)
            ) * 100,
            2
        ).alias("On_Time_Delivery_Rate"),

        # Customer Satisfaction
        round(avg("Review_Score"), 2).alias("Average_Review_Score"),

        sum(
            when(col("Review_Score") <= 2, 1)
            .otherwise(0)
        ).alias("Low_Rating_Count"),

        sum(
            when(col("Review_Score") >= 4, 1)
            .otherwise(0)
        ).alias("High_Rating_Count"),

        # Purchase Behaviour
        min("Order_Purchase_Timestamp").alias("First_Purchase_Date"),
        max("Order_Purchase_Timestamp").alias("Last_Purchase_Date")

    )

    .withColumn(
        "Customer_Lifetime_Days",
        datediff(
            col("Last_Purchase_Date"),
            col("First_Purchase_Date")
        )
    )

    .withColumn(
        "Created_Timestamp",
        current_timestamp()
    )

    .withColumn(
        "Modified_Timestamp",
        current_timestamp()
    )

)

# ============================================================
# Validate Customer Feature Table
# ============================================================

validate_dimension(
    Machine_Learning_feature_customer,
    "Machine_Learning_feature_customer"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 6:
# ============================================================
# Save Customer Feature Table
# ============================================================

(
    Machine_Learning_feature_customer.write
    .format("delta")
    .mode("overwrite")
    .saveAsTable("Machine_Learning_feature_customer")
)

print("Machine_Learning_feature_customer table created successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 7:
# ============================================================
# Reload Customer Feature Table
# ============================================================

Machine_Learning_feature_customer = spark.table(
    "Machine_Learning_feature_customer"
)

# ============================================================
# Validate Customer Feature Table
# ============================================================

validate_dimension(
    Machine_Learning_feature_customer,
    "Machine_Learning_feature_customer"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Step 4: Create Product Feature Table
# 
# ## Overview
# 
# This step creates the **Machine_Learning_feature_product** table.
# 
# The table contains one record per product and captures engineered features derived from historical sales, pricing, customer reviews, freight costs, and delivery performance.
# 
# These features provide machine learning models with product-level behavioural patterns that can be used for demand forecasting, recommendation systems, inventory optimization, pricing analytics, and product performance prediction.
# 
# ---
# 
# ## Output Table
# 
# - Machine_Learning_feature_product
# 
# ## Grain
# 
# - One row per product
# 
# ## Primary Key
# 
# - Product_SK
# 
# ---
# 
# ## Engineered Features
# 
# The following features will be generated:
# 
# - Total Orders
# - Total Quantity Sold
# - Total Revenue
# - Average Selling Price
# - Average Freight Cost
# - Average Delivery Days
# - Average Delivery Delay
# - On-Time Delivery Rate
# - Average Review Score
# - Low Rating Count
# - High Rating Count
# - First Sale Date
# - Last Sale Date
# - Product Lifecycle Days
# 
# ---
# 
# ## Business Value
# 
# This feature table enables machine learning models to:
# 
# - Predict future sales
# - Identify high-performing products
# - Detect slow-moving products
# - Build recommendation systems
# - Optimize inventory planning
# - Improve pricing strategies


# CELL ********************

# Cell 8:
# ============================================================
# Create Machine_Learning_feature_product
# ============================================================

Machine_Learning_feature_product = (

    Business_Models_fact_sales

    .groupBy("Product_SK")

    .agg(

        # Sales Performance
        countDistinct("Order_ID").alias("Total_Orders"),
        count("Order_Item_ID").alias("Total_Quantity_Sold"),

        round(
            sum("Total_Item_Value"),
            2
        ).alias("Total_Revenue"),

        round(
            avg("Price"),
            2
        ).alias("Average_Selling_Price"),

        round(
            avg("Freight_Value"),
            2
        ).alias("Average_Freight_Cost"),

        # Delivery Performance
        round(
            avg("Delivery_Days"),
            2
        ).alias("Average_Delivery_Days"),

        round(
            avg("Delivery_Delay_Days"),
            2
        ).alias("Average_Delivery_Delay"),

        round(
            avg(
                when(col("Delivery_Performance") == "On Time", 1)
                .otherwise(0)
            ) * 100,
            2
        ).alias("On_Time_Delivery_Rate"),

        # Customer Satisfaction
        round(
            avg("Review_Score"),
            2
        ).alias("Average_Review_Score"),

        sum(
            when(col("Review_Score") <= 2, 1)
            .otherwise(0)
        ).alias("Low_Rating_Count"),

        sum(
            when(col("Review_Score") >= 4, 1)
            .otherwise(0)
        ).alias("High_Rating_Count"),

        # Product Lifecycle
        min("Order_Purchase_Timestamp").alias("First_Sale_Date"),

        max("Order_Purchase_Timestamp").alias("Last_Sale_Date")

    )

    .withColumn(
        "Product_Lifecycle_Days",
        datediff(
            col("Last_Sale_Date"),
            col("First_Sale_Date")
        )
    )

    .withColumn(
        "Created_Timestamp",
        current_timestamp()
    )

    .withColumn(
        "Modified_Timestamp",
        current_timestamp()
    )

)

# ============================================================
# Validate Product Feature Table
# ============================================================

validate_dimension(
    Machine_Learning_feature_product,
    "Machine_Learning_feature_product"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 9:
# ============================================================
# Save Product Feature Table
# ============================================================

(
    Machine_Learning_feature_product.write
    .format("delta")
    .mode("overwrite")
    .saveAsTable("Machine_Learning_feature_product")
)

print("Machine_Learning_feature_product table created successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 10:
# ============================================================
# Reload Product Feature Table
# ============================================================

Machine_Learning_feature_product = spark.table(
    "Machine_Learning_feature_product"
)

# ============================================================
# Validate Product Feature Table
# ============================================================

validate_dimension(
    Machine_Learning_feature_product,
    "Machine_Learning_feature_product"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Step 5: Create Sales Feature Table
# 
# ## Overview
# 
# This step creates the **Machine_Learning_feature_sales** table.
# 
# The table contains one record per calendar day and captures daily business metrics derived from historical sales transactions.
# 
# Unlike the customer and product feature tables, this dataset is designed for time-series machine learning models where each record represents a single day.
# 
# ---
# 
# ## Output Table
# 
# - Machine_Learning_feature_sales
# 
# ## Grain
# 
# - One row per Calendar_SK (Daily Level)
# 
# ## Primary Key
# 
# - Calendar_SK
# 
# ---
# 
# ## Engineered Features
# 
# The following features will be generated:
# 
# - Total Orders
# - Total Items Sold
# - Total Revenue
# - Average Order Value
# - Average Selling Price
# - Average Freight Cost
# - Average Delivery Days
# - Average Delivery Delay
# - On-Time Delivery Rate
# - Average Review Score
# - Unique Customers
# - Unique Products
# - Unique Sellers
# 
# ---
# 
# ## Business Value
# 
# This feature table enables machine learning models to:
# 
# - Forecast future sales
# - Predict daily revenue
# - Detect seasonal trends
# - Analyze business performance
# - Support inventory planning
# - Optimize operational decisions


# CELL ********************

# Cell 11:
# ============================================================
# Create Machine_Learning_feature_sales
# ============================================================

Machine_Learning_feature_sales = (

    Business_Models_fact_sales

    .groupBy("Calendar_SK")

    .agg(

        # Sales Activity
        countDistinct("Order_ID").alias("Total_Orders"),

        count("Order_Item_ID").alias("Total_Items_Sold"),

        round(
            sum("Total_Item_Value"),
            2
        ).alias("Total_Revenue"),

        round(
            avg("Total_Item_Value"),
            2
        ).alias("Average_Order_Value"),

        # Pricing
        round(
            avg("Price"),
            2
        ).alias("Average_Selling_Price"),

        round(
            avg("Freight_Value"),
            2
        ).alias("Average_Freight_Cost"),

        # Delivery
        round(
            avg("Delivery_Days"),
            2
        ).alias("Average_Delivery_Days"),

        round(
            avg("Delivery_Delay_Days"),
            2
        ).alias("Average_Delivery_Delay"),

        round(
            avg(
                when(col("Delivery_Performance") == "On Time", 1)
                .otherwise(0)
            ) * 100,
            2
        ).alias("On_Time_Delivery_Rate"),

        # Customer Satisfaction
        round(
            avg("Review_Score"),
            2
        ).alias("Average_Review_Score"),

        # Daily Diversity
        countDistinct("Customer_SK").alias("Unique_Customers"),

        countDistinct("Product_SK").alias("Unique_Products"),

        countDistinct("Seller_SK").alias("Unique_Sellers")

    )

    .withColumn(
        "Created_Timestamp",
        current_timestamp()
    )

    .withColumn(
        "Modified_Timestamp",
        current_timestamp()
    )

)

# ============================================================
# Validate Sales Feature Table
# ============================================================

validate_dimension(
    Machine_Learning_feature_sales,
    "Machine_Learning_feature_sales"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 12:
# ============================================================
# Save Sales Feature Table
# ============================================================

(
    Machine_Learning_feature_sales.write
    .format("delta")
    .mode("overwrite")
    .saveAsTable("Machine_Learning_feature_sales")
)

print("Machine_Learning_feature_sales table created successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Step 6: Machine Learning with MLflow
# 
# ## Overview
# 
# This section introduces MLflow into the Enterprise AI Platform.
# 
# MLflow is used to manage the complete machine learning lifecycle, including:
# 
# - Experiment Tracking
# - Model Training
# - Performance Metrics
# - Model Versioning
# - Model Registry
# - Model Deployment
# 
# Rather than training models manually, every experiment performed in this notebook will be automatically tracked and stored.
# 
# ---
# 
# ## ML Models
# 
# The following models will be created:
# 
# 1. Sales Forecast Model
# 2. Customer Churn Prediction Model
# 
# ---
# 
# ## MLflow Capabilities
# 
# - Track Parameters
# - Track Metrics
# - Log Models
# - Register Models
# - Compare Experiments
# - Reuse Models
# 
# ---
# 
# ## Enterprise Benefits
# 
# Using MLflow enables:
# 
# - Reproducible experiments
# - Version-controlled models
# - Centralized model management
# - Easier collaboration
# - Production-ready deployment

# CELL ********************

# Cell 13:
# ============================================================
# Configure MLflow Experiment
# ============================================================

experiment_name = "Enterprise_AI_Platform"

mlflow.set_experiment(experiment_name)

print(f"MLflow Experiment : {experiment_name}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 14:
# ============================================================
# Reload Sales Feature Table
# ============================================================

sales_df = spark.table(
    "Machine_Learning_feature_sales"
)

# ============================================================
# Validate Sales Feature Table
# ============================================================

validate_dimension(
    sales_df,
    "Machine_Learning_feature_sales"
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# # Step 7: Train Sales Forecast Model
# 
# ## Overview
# 
# This step trains a machine learning model to predict daily sales revenue using the engineered sales features.
# 
# The model uses historical business metrics to learn relationships between sales activity and revenue.
# 
# ---
# 
# ## Objective
# 
# Predict:
# 
# - Total_Revenue
# 
# Using:
# 
# - Total_Orders
# - Total_Items_Sold
# - Average_Order_Value
# - Average_Selling_Price
# - Average_Freight_Cost
# - Average_Delivery_Days
# - Average_Delivery_Delay
# - On_Time_Delivery_Rate
# - Average_Review_Score
# - Unique_Customers
# - Unique_Products
# - Unique_Sellers
# 
# ---
# 
# ## Algorithm
# 
# - Random Forest Regressor
# 
# ---
# 
# ## Output
# 
# - Trained ML Model
# - Performance Metrics
# - MLflow Experiment

# CELL ********************

# Cell 15:
# ============================================================
# Prepare Training Dataset
# ============================================================

from pyspark.ml.feature import VectorAssembler
from pyspark.sql.functions import col

# Features used for model training
feature_columns = [

    "Total_Orders",
    "Total_Items_Sold",
    "Average_Order_Value",
    "Average_Selling_Price",
    "Average_Freight_Cost",
    "Average_Delivery_Days",
    "Average_Delivery_Delay",
    "On_Time_Delivery_Rate",
    "Average_Review_Score",
    "Unique_Customers",
    "Unique_Products",
    "Unique_Sellers"

]

# Validate source dataset
print("=" * 80)
print("Sales Feature Dataset Summary")
print("=" * 80)

print(f"Total Records : {sales_df.count()}")
print(f"Total Columns : {len(sales_df.columns)}")

# Create Feature Vector
assembler = VectorAssembler(
    inputCols=feature_columns,
    outputCol="features",
    handleInvalid="skip"
)

training_df = (
    assembler
    .transform(sales_df)
    .select(
        "features",
        col("Total_Revenue").alias("label")
    )
)

# ============================================================
# Validate Training Dataset
# ============================================================

print("=" * 80)
print("Training Dataset Summary")
print("=" * 80)

print(f"Total Records : {training_df.count()}")
print(f"Total Columns : {len(training_df.columns)}")

display(training_df.limit(10))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 16:
# ============================================================
# Split Training and Test Dataset
# ============================================================

train_df, test_df = training_df.randomSplit(
    [0.8, 0.2],
    seed=42
)

total_records = training_df.count()
train_records = train_df.count()
test_records = test_df.count()

# ============================================================
# Validate Dataset Split
# ============================================================

print("=" * 80)
print("Dataset Split Summary")
print("=" * 80)

print(f"Total Records    : {total_records}")
print(f"Training Records : {train_records}")
print(f"Testing Records  : {test_records}")

print()
print(f"Training Ratio   : {(train_records / total_records) * 100:.2f}%")
print(f"Testing Ratio    : {(test_records / total_records) * 100:.2f}%")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 17:
# ============================================================
# Train Random Forest Regression Model
# ============================================================

# Model Configuration
num_trees = 100
max_depth = 10
random_seed = 42

# Create Random Forest Regressor
rf = RandomForestRegressor(
    featuresCol="features",
    labelCol="label",
    predictionCol="prediction",
    numTrees=num_trees,
    maxDepth=max_depth,
    seed=random_seed
)

# Train Model
rf_model = rf.fit(train_df)

# ============================================================
# Training Summary
# ============================================================

print("=" * 80)
print("Random Forest Model Summary")
print("=" * 80)

print(f"Algorithm        : Random Forest Regressor")
print(f"Training Records : {train_records}")
print(f"Number of Trees  : {num_trees}")
print(f"Maximum Depth    : {max_depth}")
print(f"Random Seed      : {random_seed}")

print("\nModel trained successfully.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 18:
# ============================================================
# Generate Sales Predictions
# ============================================================

predictions_df = rf_model.transform(test_df)

# ============================================================
# Validate Predictions
# ============================================================

print("=" * 80)
print("Prediction Summary")
print("=" * 80)

print(f"Prediction Records : {predictions_df.count()}")
print(f"Total Columns      : {len(predictions_df.columns)}")

display(
    predictions_df.select(
        "label",
        "prediction"
    ).limit(10)
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 19:
# ============================================================
# Evaluate Random Forest Model
# ============================================================

from pyspark.ml.evaluation import RegressionEvaluator

rmse = RegressionEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="rmse"
).evaluate(predictions_df)

mae = RegressionEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="mae"
).evaluate(predictions_df)

r2 = RegressionEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="r2"
).evaluate(predictions_df)

print("=" * 80)
print("Random Forest Model Performance")
print("=" * 80)

print(f"RMSE : {rmse:.2f}")
print(f"MAE  : {mae:.2f}")
print(f"R²   : {r2:.4f}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 20:
# ============================================================
# Log Model with MLflow
# ============================================================

import mlflow
import mlflow.spark

with mlflow.start_run(run_name="Sales_Forecast_RandomForest"):

    # --------------------------------------------------------
    # Log Parameters
    # --------------------------------------------------------

    mlflow.log_param("Algorithm", "Random Forest Regressor")
    mlflow.log_param("Number_of_Trees", num_trees)
    mlflow.log_param("Maximum_Depth", max_depth)
    mlflow.log_param("Random_Seed", random_seed)

    # --------------------------------------------------------
    # Log Metrics
    # --------------------------------------------------------

    mlflow.log_metric("RMSE", rmse)
    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("R2", r2)

    # --------------------------------------------------------
    # Log Model
    # --------------------------------------------------------

    mlflow.spark.log_model(
        spark_model=rf_model,
        artifact_path="RandomForestModel"
    )

print("=" * 80)
print("MLflow Logging Summary")
print("=" * 80)

print("Run Name      : Sales_Forecast_RandomForest")
print("Experiment    : Enterprise_AI_Platform")
print("Status        : Successfully Logged")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 21:
# ============================================================
# Create Machine Learning Prediction Table
# ============================================================

from pyspark.ml.feature import VectorAssembler
from pyspark.sql.functions import (
    col,
    abs,
    current_timestamp
)

# ------------------------------------------------------------
# Read Sales Feature Table
# ------------------------------------------------------------

sales_df = spark.table(
    "Machine_Learning_feature_sales"
)

# ------------------------------------------------------------
# Create Feature Vector
# ------------------------------------------------------------

feature_columns = [

    "Total_Orders",
    "Total_Items_Sold",
    "Average_Order_Value",
    "Average_Selling_Price",
    "Average_Freight_Cost",
    "Average_Delivery_Days",
    "Average_Delivery_Delay",
    "On_Time_Delivery_Rate",
    "Average_Review_Score",
    "Unique_Customers",
    "Unique_Products",
    "Unique_Sellers"

]

assembler = VectorAssembler(
    inputCols=feature_columns,
    outputCol="features",
    handleInvalid="skip"
)

sales_prediction_df = assembler.transform(sales_df)

# ------------------------------------------------------------
# Generate Predictions
# ------------------------------------------------------------

Machine_Learning_prediction_sales = (
    rf_model
    .transform(sales_prediction_df)
    .select(
        "Calendar_SK",
        col("Total_Revenue").alias("Actual_Revenue"),
        col("prediction").alias("Predicted_Revenue")
    )
    .withColumn(
        "Prediction_Error",
        abs(
            col("Actual_Revenue") -
            col("Predicted_Revenue")
        )
    )
    .withColumn(
        "Prediction_Timestamp",
        current_timestamp()
    )
)

# ------------------------------------------------------------
# Save Prediction Table
# ------------------------------------------------------------

Machine_Learning_prediction_sales.write \
    .format("delta") \
    .mode("overwrite") \
    .saveAsTable("Machine_Learning_prediction_sales")

print("=" * 80)
print("Prediction Table Created Successfully")
print("=" * 80)

print("Table Name : Machine_Learning_prediction_sales")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Cell 22:
# ============================================================
# Validate Machine Learning Prediction Table
# ============================================================

Machine_Learning_prediction_sales = spark.table(
    "Machine_Learning_prediction_sales"
)

print("=" * 80)
print("Machine Learning Prediction Sales Summary")
print("=" * 80)

print(f"Total Records : {Machine_Learning_prediction_sales.count()}")
print(f"Total Columns : {len(Machine_Learning_prediction_sales.columns)}")

display(
    Machine_Learning_prediction_sales.limit(10)
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
